cacheFolder: "C:\\Users\\Administrator\\AppData\\Local\\Yarn\\Berry\\cache"

globalFolder: "C:\\Users\\Administrator\\AppData\\Local\\Yarn\\Berry"

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmmirror.com"
