/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  mySidebar: [
    {
      type: 'category',
      label: '📘知识库',
      link: { type: 'doc', id: 'intro' },
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '.', // Generate sidebar slice from .
        },
      ],
    },
  ], // 自动生成侧边栏
}

// const sidebars: SidebarsConfig = {
//   /*   testSidebar: [
//     'introduction',
//     {
//       type: 'category',
//       label: 'Getting Started',
//       link: {
//         type: 'generated-index',
//       },
//       collapsed: false,
//       items: ['intro'],
//     },
//     {
//       type: 'category',
//       label: 'Guides',
//       link: {
//         type: 'generated-index',
//         title: 'Docusaurus Guides',
//         description: "Let's learn about the most important Docusaurus concepts!",
//         keywords: ['guides'],
//         image: '/img/docusaurus.png',
//       },
//       items: [
//         'guides/creating-pages',
//         {
//           type: 'category',
//           label: 'Docs',
//           link: {
//             type: 'doc',
//             id: 'guides/docs/introduction',
//           },
//           items: [
//             'guides/docs/create-doc',
//             {
//               type: 'category',
//               label: 'Sidebar',
//               link: {
//                 type: 'doc',
//                 id: 'guides/docs/sidebar/index',
//               },
//               items: [
//                 'guides/docs/sidebar/items',
//                 'guides/docs/sidebar/autogenerated',
//                 'guides/docs/sidebar/multiple-sidebars',
//               ],
//             },
//             'guides/docs/versioning',
//             'guides/docs/multi-instance',
//           ],
//         },
//         'blog',
//         {
//           type: 'category',
//           label: 'Markdown Features',
//           link: {
//             type: 'doc',
//             id: 'guides/markdown-features/introduction',
//           },
//           items: [
//             'guides/markdown-features/react',
//             'guides/markdown-features/tabs',
//             'guides/markdown-features/code-blocks',
//             'guides/markdown-features/admonitions',
//             'guides/markdown-features/toc',
//             'guides/markdown-features/assets',
//             'guides/markdown-features/links',
//             'guides/markdown-features/plugins',
//             'guides/markdown-features/math-equations',
//             'guides/markdown-features/diagrams',
//             'guides/markdown-features/head-metadata',
//           ],
//         },
//         'styling-layout',
//         'swizzling',
//         'static-assets',
//         'search',
//         'browser-support',
//         'seo',
//         'using-plugins',
//         'deployment',
//         {
//           type: 'category',
//           label: 'Internationalization',
//           link: { type: 'doc', id: 'i18n/introduction' },
//           items: [
//             {
//               type: 'doc',
//               id: 'i18n/tutorial',
//               label: 'Tutorial',
//             },
//             {
//               type: 'doc',
//               id: 'i18n/git',
//               label: 'Using Git',
//             },
//             {
//               type: 'doc',
//               id: 'i18n/crowdin',
//               label: 'Using Crowdin',
//             },
//           ],
//         },
//         'guides/whats-next',
//       ],
//     },
//     {
//       type: 'category',
//       label: 'Advanced Guides',
//       link: { type: 'doc', id: 'advanced/index' },
//       items: ['advanced/architecture', 'advanced/plugins', 'advanced/routing', 'advanced/ssg', 'advanced/client'],
//     },
//     {
//       type: 'category',
//       label: 'Upgrading',
//       link: {
//         type: 'doc',
//         id: 'migration/index',
//       },
//       items: [
//         'migration/v3',
//         {
//           type: 'category',
//           label: 'To Docusaurus v2',
//           items: [
//             'migration/v2/migration-overview',
//             'migration/v2/migration-automated',
//             'migration/v2/migration-manual',
//             'migration/v2/migration-versioned-sites',
//             'migration/v2/migration-translated-sites',
//           ],
//         },
//       ],
//     },
//   ], */
//   // mySidebar3: [
//   //   {
//   //     type: 'category',
//   //     label: '📘知识库',
//   //     // link: {
//   //     //   type: 'generated-index',
//   //     // },
//   //     link: { type: 'doc', id: 'intro' },
//   //     collapsed: false,
//   //     items: [
//   //       /*'intro',*/
//   //       {
//   //         type: 'autogenerated',
//   //         dirName: '.', // Generate sidebar slice from .
//   //       },
//   //     ],
//   //   },
//   //   /*'intro',*/
//   //   // {
//   //   //   type: 'autogenerated',
//   //   //   dirName: '.', // Generate sidebar slice from .
//   //   // },
//   //   // {
//   //   //   type: 'category',
//   //   //   label: '第一组',
//   //   //   items: [
//   //   //     '第一组-intro',
//   //   //     {
//   //   //       type: 'autogenerated',
//   //   //       dirName: 'tutorials/easy', // Generate sidebar slice from docs/tutorials/easy
//   //   //     },
//   //   //     '第一组-中间文档',
//   //   //     {
//   //   //       type: 'autogenerated',
//   //   //       dirName: 'tutorials/advanced', // Generate sidebar slice from docs/tutorials/advanced
//   //   //     },
//   //   //     '第一组-结尾文档',
//   //   //   ],
//   //   // },
//   //   // {
//   //   //   type: 'autogenerated',
//   //   //   dirName: 'api', // Generate sidebar slice from docs/api
//   //   // },
//   //   // {
//   //   //   type: 'category',
//   //   //   label: 'Community',
//   //   //   items: ['team', 'chat'],
//   //   // },
//   //   // {
//   //   //   type: 'category',
//   //   //   label: '我的知识库',
//   //   //   link: { type: 'doc', id: 'firstPage' },
//   //   //   items: [],
//   //   // },
//   //   // {
//   //   //   type: 'autogenerated',
//   //   //   dirName: '.',
//   //   //   /*---------------------------------------------------- */
//   //   //   //   type: 'category', //分类侧边栏 必填
//   //   //   //   label: 'Guides', // Sidebar label text. string类型必填
//   //   //   //   // className:'/'   // 可选css类名称
//   //   //   //   // description: '这是一个分类侧边栏示例。', //可选参数
//   //   //   //   // Category options:
//   //   //   //   collapsible: true, // 将类别设置为可折叠的
//   //   //   //   collapsed: false, // 将类别设置为初始折叠或默认打开
//   //   //   //   // link: SidebarItemCategoryLinkDoc | SidebarItemCategoryLinkGeneratedIndex;
//   //   //   //   link: {
//   //   //   //     type: 'generated-index',
//   //   //   //     title: 'Docusaurus Guides',
//   //   //   //     description: "Let's learn about the most important Docusaurus concepts!",
//   //   //   //     keywords: ['guides'],
//   //   //   //     image: '/img/docusaurus.png',
//   //   //   //   },
//   //   //   //   items: [
//   //   //   //     ' introduction',
//   //   //   //     // {
//   //   //   //     //   type: 'category',
//   //   //   //     //   label: 'Docs',
//   //   //   //     //   items: ['introduction', 'sidebar', 'markdown-features', 'versioning'],
//   //   //   //     // },
//   //   //   //   ], //Array of sidebar items.
//   //   // },
//   // ], // 自动生成侧边栏
//   // myLinksSidebar: [
//   //   // 外部链接
//   //   {
//   //     type: 'link', //必选参数
//   //     label: 'Facebook', // The link label 必选参数
//   //     href: 'https://facebook.com', // The external URL 必选参数
//   //     className: '/', //可选参数
//   //     description: 'FaceBook官方网站', //可选参数
//   //   },
//   //   // 内部链接
//   //   {
//   //     type: 'link', //必选参数
//   //     label: 'Home', // The link label 必选参数
//   //     href: '/', // The internal path 必选参数
//   //     className: '/', //可选参数
//   //     description: '网站首页', //可选参数
//   //   },
//   // ],
//   // myDocsSidebar_example: [
//   //   /* ------------------------------------------------------ */
//   //   /*doc文档模式侧边栏条目 完整语法*/
//   //   {
//   //     type: 'doc', // 必选参数
//   //     id: 'doc1', // 文档ID 必选参数
//   //     label: 'Getting started', // 侧边栏标签文字 必选参数
//   //     //className?: string; // Class name for sidebar label 可选参数
//   //     //customProps?: Record<string, unknown>; // Custom props 可选参数
//   //   },
//   //   /*doc文档模式侧边栏条目 简写语法*/
//   //   'doc2', // 文档ID 必选参数
//   //   /* ------------------------------------------------------ */
//   // ],
//   // myCategorySideBar_example: [
//   //   {
//   //     type: 'category', //分类侧边栏 必填
//   //     label: 'Guides', // Sidebar label text. string类型必填
//   //     // className:'/'   // 可选css类名称
//   //     // description: '这是一个分类侧边栏示例。', //可选参数
//   //     // Category options:
//   //     collapsible: true, // 将类别设置为可折叠的
//   //     collapsed: false, // 将类别设置为初始折叠或默认打开
//   //     // link: SidebarItemCategoryLinkDoc | SidebarItemCategoryLinkGeneratedIndex;
//   //     link: {
//   //       type: 'generated-index',
//   //       title: 'Docusaurus Guides',
//   //       description: "Let's learn about the most important Docusaurus concepts!",
//   //       keywords: ['guides'],
//   //       image: '/img/docusaurus.png',
//   //     },
//   //     items: [
//   //       'overview',
//   //       // {
//   //       //   type: 'category',
//   //       //   label: 'Docs',
//   //       //   items: ['introduction', 'sidebar', 'markdown-features', 'versioning'],
//   //       // },
//   //     ], //Array of sidebar items.
//   //   },
//   // ],
//   // Sidebar_example: [
//   //   {
//   //     type: 'category', //分类侧边栏条目
//   //     label: 'Getting Started',
//   //     link: {
//   //       type: 'generated-index',
//   //     },
//   //     collapsed: false,
//   //     items: ['installation', 'configuration', 'playground', 'typescript-support'],
//   //   },
//   //   {
//   //     type: 'category', //分类侧边栏条目
//   //     label: 'Guides',
//   //     link: {
//   //       type: 'generated-index',
//   //       title: 'Docusaurus Guides',
//   //       description: "Let's learn about the most important Docusaurus concepts!",
//   //       keywords: ['guides'],
//   //       image: '/img/docusaurus.png',
//   //     },
//   //     items: [
//   //       {
//   //         type: 'category',
//   //         label: 'Docs',
//   //         link: {
//   //           type: 'doc',
//   //           id: 'guides/docs/introduction',
//   //         },
//   //         items: [
//   //           {
//   //             type: 'category',
//   //             label: 'Sidebar',
//   //             link: {
//   //               type: 'doc',
//   //               id: 'guides/docs/sidebar/index',
//   //             },
//   //             items: [
//   //               'guides/docs/sidebar/items',
//   //               'guides/docs/sidebar/autogenerated',
//   //               'guides/docs/sidebar/multiple-sidebars',
//   //             ],
//   //           },
//   //         ],
//   //       },
//   //       {
//   //         type: 'category',
//   //         label: 'Markdown Features',
//   //         link: {
//   //           type: 'doc',
//   //           id: 'guides/markdown-features/introduction',
//   //         },
//   //         items: [
//   //           'guides/markdown-features/react',
//   //           'guides/markdown-features/tabs',
//   //           'guides/markdown-features/code-blocks',
//   //           'guides/markdown-features/admonitions',
//   //           'guides/markdown-features/toc',
//   //           'guides/markdown-features/assets',
//   //           'guides/markdown-features/links',
//   //           'guides/markdown-features/plugins',
//   //           'guides/markdown-features/math-equations',
//   //           'guides/markdown-features/diagrams',
//   //           'guides/markdown-features/head-metadata',
//   //         ],
//   //       },
//   //       {
//   //         type: 'category',
//   //         label: 'Internationalization',
//   //         link: { type: 'doc', id: 'i18n/introduction' },
//   //         items: [
//   //           {
//   //             type: 'doc',
//   //             id: 'i18n/tutorial',
//   //             label: 'Tutorial',
//   //           },
//   //           {
//   //             type: 'doc',
//   //             id: 'i18n/git',
//   //             label: 'Using Git',
//   //           },
//   //           {
//   //             type: 'doc',
//   //             id: 'i18n/crowdin',
//   //             label: 'Using Crowdin',
//   //           },
//   //         ],
//   //       },
//   //     ],
//   //   },
//   //   {
//   //     type: 'category', //分类侧边栏条目
//   //     label: 'Advanced Guides',
//   //     link: { type: 'doc', id: 'advanced/index' },
//   //     items: ['advanced/architecture', 'advanced/plugins', 'advanced/routing', 'advanced/ssg', 'advanced/client'],
//   //   },
//   //   {
//   //     type: 'category', //分类侧边栏条目
//   //     label: 'Upgrading',
//   //     link: {
//   //       type: 'doc',
//   //       id: 'migration/index',
//   //     },
//   //     items: [
//   //       'migration/v3',
//   //       {
//   //         type: 'category',
//   //         label: 'To Docusaurus v2',
//   //         items: [
//   //           'migration/v2/migration-overview',
//   //           'migration/v2/migration-automated',
//   //           'migration/v2/migration-manual',
//   //           'migration/v2/migration-versioned-sites',
//   //           'migration/v2/migration-translated-sites',
//   //         ],
//   //       },
//   //     ],
//   //   },
//   // ],
//   // Sidebar_example2: [
//   //   'cli',
//   //   'docusaurus-core',
//   //   {
//   //     type: 'autogenerated', //自动生成-侧边栏条目
//   //     dirName: 'api',
//   //   },
//   // ],
// }

module.exports = sidebars

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure

//   //笔记数据
//   linux: [{ type: 'autogenerated', dirName: '1、笔记数据' }],
//   // docs: [
//   //   {
//   //     type: 'category',
//   //     label: '教程',
//   //     link: {
//   //       type: 'generated-index',
//   //       title: 'Docusaurus 教程',
//   //       description: '学习最重要的 Docusaurus 概念!',
//   //       slug: '/category/docusaurus-guides',
//   //       keywords: ['guides'],
//   //       image: '/img/docusaurus.png',
//   //     },
//   //     items: ['1、笔记数据/1、运维/linux/1、linux/1、linux命令/2、linux-pid-command',
//   //         '1、笔记数据/1、运维/linux/1、linux/1、linux命令/3、网络管理',
//   //         '1、笔记数据/1、运维/linux/1、linux/1、linux命令/4、磁盘管理',
//   //         '1、笔记数据/1、运维/linux/1、linux/1、linux命令/5、linux命令(按字母排序)',
//   //         '1、笔记数据/1、运维/linux/1、linux/1、linux命令/文件管理',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/1、shell/1、shell语法',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/1、shell/2、shell排错',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/2、shell三剑客/1、awk',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/2、shell三剑客/2、sed',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/2、shell三剑客/3、grep',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/3、正则表达式/正则表达式',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/1、shell脚本/00、运维脚本',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/1、shell脚本/1、自动配置ip与主机名脚本',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/1、shell脚本/2024.4.1-Linux基线加固',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/1、shell脚本/2、kind创建的k8s集群安装argocd脚本',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/1、shell脚本/Centos7初始化脚本',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/1、shell脚本/cat结合EOF',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/1、shell脚本/centos7源码编译安装python3.8.6',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/1、shell脚本/history',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/1、shell脚本/linux批量ping',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/1、shell脚本/mysql一键安装/1、实战：一键安装mysql-5.6二进制包脚本(mysql-5.6.42)(测试成功)',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/1、shell脚本/mysql一键安装/2、实战：一键安装mysql-5.7二进制包脚本(mysql-5.7.29)(测试成功)',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/1、shell脚本/ssh升级/实战：centos7.9-ssh86升级-2022.12.27(测试成功)',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/1、shell脚本/内核升级',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/1、shell脚本/删库跑路之命令RmToMv的安全实现',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/1、shell脚本/数据库备份/1、mysql备份/MySQL数据库异地备份与恢复脚本-2024.1.13(收藏)',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/1、shell脚本/数据库备份/PostgreSQL数据库异地备份与恢复脚本-2024.1.13(收藏)',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/1、shell脚本/数据库备份/生产级Oracle数据库备份Shell脚本-2024.1.13(收藏)',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/1、shell脚本/磁盘划分',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/1、shell脚本/网卡bond配置',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/2、python脚本/ipmi批量操作服务器',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/2、python脚本/python脚本',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/2、python脚本/批量上传和下载文件/1、批量上传脚本',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/2、python脚本/批量上传和下载文件/2、批量下载脚本',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/2、python脚本/批量创建文件夹',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/2、python脚本/批量执行linux命令/0、批量执行linux命令',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/2、python脚本/批量执行linux命令/1、批量修改主机名',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/2、python脚本/批量执行linux命令/2、批量修改ip',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/2、python脚本/搜集物理服务器光衰',
//   //         '1、笔记数据/1、运维/linux/1、linux/2、shell/4、shell脚本/2、python脚本/集成工程线缆检查脚本',
//   //         '1、笔记数据/1、运维/linux/1、linux/3、监控/1、zabbix/zabbix',
//   //         '1、笔记数据/1、运维/linux/1、linux/3、监控/2、prometheus/prometheus',
//   //         '1、笔记数据/1、运维/linux/1、linux/3、监控/2、prometheus/实战-Centos安装prometheus-grafana-2020.11.27(测试成功)',
//   //         '1、笔记数据/1、运维/linux/1、linux/3、监控/grafna/grafna',
//   //         '1、笔记数据/1、运维/linux/1、linux/4、日志/日志',
//   //         '1、笔记数据/1、运维/linux/1、linux/5、git/1、git/1、安装/1、实战：windows安装git-2022.5.4(测试成功)',
//   //         '1、笔记数据/1、运维/linux/1、linux/5、git/1、git/1、安装/2、实战：Linux服务器安装Git-2022.5.7(测试成功)',
//   //         '1、笔记数据/1、运维/linux/1、linux/5、git/1、git/2、使用/git命令',
//   //         '1、笔记数据/1、运维/linux/1、linux/5、git/1、git/3、排错/TS：从 Git 2.0 开始，push.default 的默认值将从 matching 改为 simple-2024.6.2(已解决)',
//   //         '1、笔记数据/1、运维/linux/1、linux/5、git/1、git/3、排错/git排错',
//   //         '1、笔记数据/1、运维/linux/1、linux/5、git/2、svn/svn',
//   //         '1、笔记数据/1、运维/linux/1、linux/5、git/版本控制平台/1、github/1、github',
//   //         '1、笔记数据/1、运维/linux/1、linux/5、git/版本控制平台/2、gitee/gitee',
//   //         '1、笔记数据/1、运维/linux/1、linux/5、git/版本控制平台/2、gitee/如何维护一个属于自己的开源项目/2、代码贡献',
//   //         '1、笔记数据/1、运维/linux/1、linux/5、git/版本控制平台/3、coding/coding',
//   //         '1、笔记数据/1、运维/linux/1、linux/6、数据库/1、Mysql/1、安装/1、yum/yum安装mysql',
//   //         '1、笔记数据/1、运维/linux/1、linux/6、数据库/1、Mysql/1、安装/2、二进制/1、实战：通用二进制格式安装 MySQL(mysql-5.6.47)-2024.4.6(测试成功)',
//   //         '1、笔记数据/1、运维/linux/1、linux/6、数据库/1、Mysql/1、安装/2、二进制/2、实战：通用二进制格式安装 MySQL(mysql-5.7.29)-2024.4.6(测试成功)',
//   //         '1、笔记数据/1、运维/linux/1、linux/6、数据库/1、Mysql/1、安装/2、二进制/3、实战：Centos7配置mysql多实例(mysql-5.7.42)-2024.4.20(测试成功)',
//   //         '1、笔记数据/1、运维/linux/1、linux/6、数据库/1、Mysql/1、安装/2、二进制/4、mysql安装注意事项',
//   //         '1、笔记数据/1、运维/linux/1、linux/6、数据库/1、Mysql/2、使用/1、Mysql',
//   //         '1、笔记数据/1、运维/linux/1、linux/6、数据库/1、Mysql/2、使用/2、mysql命令',
//   //         '1、笔记数据/1、运维/linux/1、linux/6、数据库/1、Mysql/2、使用/3、mysql faq',
//   //         '1、笔记数据/1、运维/linux/1、linux/6、数据库/1、Mysql/3、排错/mysql排错',
//   //         '1、笔记数据/1、运维/linux/1、linux/6、数据库/1、Mysql/4、sql脚本/范例-生成数据库表大文件脚本',
//   //         '1、笔记数据/1、运维/linux/1、linux/6、数据库/2、Oracle/1、oracle',
//   //         '1、笔记数据/1、运维/linux/1、linux/6、数据库/2、Oracle/2、multipath-多路径软件',
//   //         '1、笔记数据/1、运维/linux/1、linux/6、数据库/3、etcd/etcd',
//   //         '1、笔记数据/1、运维/linux/1、linux/6、数据库/4、MariaDB/1、MariaDB安装/1、实战：MariaDB部署(yum方式)-2024.3.28(测试成功)',
//   //         '1、笔记数据/1、运维/linux/1、linux/6、数据库/4、MariaDB/1、MariaDB安装/2、实战：源码编译安装mariadb(10.2.19)-2024.4.18(测试成功)',
//   //         '1、笔记数据/1、运维/linux/linux-cover',
//   //         '1、笔记数据/2、编程/md',
//   //         '1、笔记数据/知识库',
//   //         '2、开源项目/1、玩转Typora/4、使用',
//   //         '2、开源项目/1、玩转Typora/5、全网最美typora主题-one',
//   //         '2、开源项目/1、玩转Typora/6、Typora主题测试文件',
//   //         '3、专题/01、网站搭建/A001',
//   //         '3、专题/02、云笔记最佳实践/1、云笔记最佳实践',
//   //         '3、专题/02、云笔记最佳实践/项目1',
//   //         '3、专题/05、NAS/项目1',
//   //         '3、专题/06、前端示例/项目1',
//   //         '8、已整理/Docusaurus/Docusaurus-Footer',
//   //         '8、已整理/Docusaurus/Docusaurus-NavFilter',
//   //         '8、已整理/Docusaurus/Docusaurus-UpdateTime',
//   //         '8、已整理/Docusaurus/Docusaurus-back-top',
//   //         '8、已整理/Docusaurus/Docusaurus-guides',
//   //         '8、已整理/Docusaurus/Docusaurus-jest',
//   //         '8、已整理/Docusaurus/Docusaurus-menulist',
//   //         '8、已整理/Docusaurus/Docusaurus-pagination-nav-link',
//   //         '8、已整理/Docusaurus/Docusaurus-scrollbar',
//   //         '8、已整理/Docusaurus/Docusaurus-table-of-contents__link',
//   //         '8、已整理/Docusaurus/docusaurus-comment',
//   //         '8、已整理/Docusaurus/docusaurus-component',
//   //         '8、已整理/Docusaurus/docusaurus-config',
//   //         '8、已整理/Docusaurus/docusaurus-deploy',
//   //         '8、已整理/Docusaurus/docusaurus-guides-kuizuo',
//   //         '8、已整理/Docusaurus/docusaurus-plugin',
//   //         '8、已整理/Docusaurus/docusaurus-search',
//   //         '8、已整理/Docusaurus/docusaurus-style',
//   //         '9、待整理/00待处理的事件',
//   //         '9、待整理/9、文件中转编辑区/picgo',
//   //         '9、待整理/9、文件中转编辑区/wenj3',
//   //         '9、待整理/9、文件中转编辑区/一些链接',
//   //         '9、待整理/Blog/introduction',
//   //         '9、待整理/Blog/tutorial/BT/Detailed',
//   //         '9、待整理/Blog/tutorial/Ruyu-Blog/Gitee',
//   //         '9、待整理/Blog/tutorial/Ruyu-Blog/Music-module',
//   //         '9、待整理/Blog/tutorial/Ruyu-Blog/Ruyu-Blog',
//   //         '9、待整理/Blog/tutorial/Ruyu-Blog/hitokoto',
//   //         '9、待整理/Blog/tutorial/index',
//   //         '9、待整理/Docusaurus 3.5',
//   //         '9、待整理/EfficiencyGuide/Tool/Tool-blank',
//   //         '9、待整理/EfficiencyGuide/introduction',
//   //         '9、待整理/F  docusaurus 纱线开始',
//   //         '9、待整理/Hugo 永久链接',
//   //         '9、待整理/LifeGuide/introduction',
//   //         '9、待整理/Site/Docusaurus/Docusaurus-使用Hygen创建文章模板',
//   //         '9、待整理/Site/Docusaurus/Docusaurus-图床配置',
//   //         '9、待整理/Site/Docusaurus/Docusaurus-搜索配置',
//   //         '9、待整理/Site/Docusaurus/Docusaurus-样式与页面',
//   //         '9、待整理/Site/Docusaurus/Docusaurus-自定义组件',
//   //         '9、待整理/Site/Docusaurus/Docusaurus-评论系统',
//   //         '9、待整理/Site/Docusaurus/Docusaurus-部署',
//   //         '9、待整理/Site/Docusaurus/guides',
//   //         '9、待整理/Site/Hexo/Hexo-Vercel部署',
//   //         '9、待整理/Site/Hexo/Hexo-主题安装',
//   //         '9、待整理/Site/Hexo/Hexo-部署',
//   //         '9、待整理/Site/Test/docusaurus111/docusaurus111-comment',
//   //         '9、待整理/Site/Test/docusaurus111/docusaurus111-comment1',
//   //         '9、待整理/Site/Test/docusaurus111/docusaurus111-component',
//   //         '9、待整理/Site/Test/docusaurus111/docusaurus111-config',
//   //         '9、待整理/Site/Test/docusaurus111/docusaurus111-deploy',
//   //         '9、待整理/Site/Test/docusaurus111/docusaurus111-plugin',
//   //         '9、待整理/Site/Test/docusaurus111/docusaurus111-search',
//   //         '9、待整理/Site/Test/docusaurus111/docusaurus111-searchcopy',
//   //         '9、待整理/Site/Test/docusaurus111/docusaurus222/docusaurus222-config',
//   //         '9、待整理/Site/Test/introduction',
//   //         '9、待整理/Site/Tips/Docusaurus-获取网站 favicon 图标',
//   //         '9、待整理/Site/introduction',
//   //         '9、待整理/Stack/C_C++/blank',
//   //         '9、待整理/Stack/Linux/Linux-Ubuntu 18.04 无法修改分辨率的问题',
//   //         '9、待整理/Stack/Linux/Linux-Ubuntu 使用命令行从远程服务器复制文件',
//   //         '9、待整理/Stack/Linux/Linux-Ubuntu 使用命令行挂载、弹出U盘',
//   //         '9、待整理/Stack/Linux/Linux-Ubuntu 安装 NVIDIA 显卡驱动',
//   //         '9、待整理/Stack/Linux/Linux-Ubuntu 安装 glog 与 gflag',
//   //         '9、待整理/Stack/Linux/Linux-Ubuntu 安装并配置 zsh、on-my-zsh 🚧️',
//   //         '9、待整理/Stack/Linux/Linux-Ubuntu 更换软件源',
//   //         '9、待整理/Stack/Linux/Linux-Ubuntu 缺少 ifconfig 命令',
//   //         '9、待整理/Stack/Linux/Linux-Ubuntu录制GIF',
//   //         '9、待整理/Stack/Linux/Linux-win10安装Ubuntu20.04',
//   //         '9、待整理/Stack/Linux/Linux-如何制作Ubuntu启动盘',
//   //         '9、待整理/Stack/Linux/Linux-打开终端报错：LD_PRELOAD cannot be preloaded',
//   //         '9、待整理/Stack/PlanningControl/blank',
//   //         '9、待整理/Stack/ROS/Tips/Tips-ROS每次都要source的问题',
//   //         '9、待整理/Stack/ROS/Tips/Tips-roslaunch时功能包与launch文件重名的问题',
//   //         '9、待整理/Stack/ROS/Tips/Tips-rosrun、roslaunch命令Tab自动补齐失效.md',
//   //         '9、待整理/Stack/ROS/blank',
//   //         '9、待整理/Stack/STM32/blank',
//   //         '9、待整理/Stack/introduction',
//   //         '9、待整理/Typora可以自动添加slug吗',
//   //         '9、待整理/Untitled',
//   //         '9、待整理/WildWolf/introduction',
//   //         '9、待整理/WildWolf/letter/letter-写在即将离别的时候',
//   //         '9、待整理/WildWolf/letter/letter-留给机器人队的「家书」- 2021',
//   //         '9、待整理/Write_Something/HelloBlog',
//   //         '9、待整理/Write_Something/如何更好地面向对象',
//   //         '9、待整理/Write_Something/深圳小记',
//   //         '9、待整理/develop/AutoHotkey键盘映射',
//   //         '9、待整理/develop/HTTP请求之Content-Type',
//   //         '9、待整理/develop/HTTP请求配置客户端SSL证书',
//   //         '9、待整理/develop/JS代码之混淆',
//   //         '9、待整理/develop/JS代码之还原',
//   //         '9、待整理/develop/JS函数hook',
//   //         '9、待整理/develop/JavaScript中的二进制数据',
//   //         '9、待整理/develop/MongoDB按时间分组',
//   //         '9、待整理/develop/RPC远程调用浏览器函数',
//   //         '9、待整理/develop/React Native 开发心得分享',
//   //         '9、待整理/develop/Redis获取六位不重复数字（邀请码）',
//   //         '9、待整理/develop/Rust实现MD5加密并打包成WebAssembly调用',
//   //         '9、待整理/develop/SSE 服务器发送事件',
//   //         '9、待整理/develop/SpringBoot热更新',
//   //         '9、待整理/develop/Vite使用WebWorker',
//   //         '9、待整理/develop/creategiteerepo',
//   //         '9、待整理/develop/nest.js 添加 swagger 响应数据文档',
//   //         '9、待整理/develop/node与浏览器中的cookie',
//   //         '9、待整理/develop/pnpm monorepo实践',
//   //         '9、待整理/develop/rollup.js初体验',
//   //         '9、待整理/develop/代码备份方案',
//   //         '9、待整理/develop/使用Github Action自动化部署',
//   //         '9、待整理/develop/使用JSONPath解析json数据',
//   //         '9、待整理/develop/前端测试',
//   //         '9、待整理/develop/基于Axios封装HTTP类库',
//   //         '9、待整理/develop/开源许可证',
//   //         '9、待整理/develop/有了 Prisma 就别用 TypeORM 了',
//   //         '9、待整理/develop/服务器与域名备案',
//   //         '9、待整理/develop/模拟请求 协议复现方案',
//   //         '9、待整理/develop/浅谈HTTP',
//   //         '9、待整理/develop/记一次git丢失代码找回',
//   //         '9、待整理/docker/Docker部署Frp内网穿透教程',
//   //         '9、待整理/docus01',
//   //         '9、待整理/life/如何在羊群里保护好自己',
//   //         '9、待整理/life/记录一次皮肤感染',
//   //         '9、待整理/lifestyle/MacBook 体验有感',
//   //         '9、待整理/lifestyle/myfirstlifestyleblog',
//   //         '9、待整理/lifestyle/一位未曾涉足算法的初学者收获',
//   //         '9、待整理/lifestyle/为什么我不用七牛云',
//   //         '9、待整理/lifestyle/为何我选择日夜颠倒敲代码',
//   //         '9、待整理/lifestyle/关于 restful api 路径定义的思考',
//   //         '9、待整理/lifestyle/正被消磨殆尽的耐心',
//   //         '9、待整理/lifestyle/浅谈个人学习方式',
//   //         '9、待整理/lifestyle/深谈个人对新技术的看法',
//   //         '9、待整理/lifestyle/记 Github 学生认证',
//   //         '9、待整理/lifestyle/记 · 在 AI 公司入职一个月的体验与感悟',
//   //         '9、待整理/lifestyle/记一次Github提交PR过程',
//   //         '9、待整理/lifestyle/记一次前端面试过程',
//   //         '9、待整理/lifestyle/谈易语言',
//   //         '9、待整理/lifestyle/距离我上篇笔记还是在',
//   //         '9、待整理/myfirstblog',
//   //         '9、待整理/plist',
//   //         '9、待整理/program/Chrome插件开发',
//   //         '9、待整理/program/Deno不只是个Javascript运行时',
//   //         '9、待整理/program/Gitea 与 Drone 实践',
//   //         '9、待整理/program/GraphQL实践',
//   //         '9、待整理/program/Nest grpc 实践之调用 python ddddocr 库',
//   //         '9、待整理/program/Next.js项目搭建与部署',
//   //         '9、待整理/program/SpringBoot项目结构',
//   //         '9、待整理/program/Strapi 实现用户注册与登录',
//   //         '9、待整理/program/Typescript 全栈最值得学习的技术栈 TRPC',
//   //         '9、待整理/program/Vercel部署Serverless',
//   //         '9、待整理/program/Vercel部署个人博客',
//   //         '9、待整理/program/vite+vue3搭建uniapp开发环境',
//   //         '9、待整理/program/使用 Fresh 框架构建 Web 应用',
//   //         '9、待整理/program/使用Vue开发Chrome插件',
//   //         '9、待整理/program/将 Supabase 作为下一个后端服务',
//   //         '9、待整理/program/搭建Electron+Vue3开发环境',
//   //         '9、待整理/program/搭建GitLab代码管理仓库',
//   //         '9、待整理/program/第一个博客搭建之Vuepress',
//   //         '9、待整理/program/第二个博客搭建之Docusaurus',
//   //         '9、待整理/program/记ThinkPHP项目部署',
//   //         '9、待整理/project/API-Service接口服务',
//   //         '9、待整理/project/Protocol 协议复现模板',
//   //         '9、待整理/project/myfirstProjectblog',
//   //         '9、待整理/project/nest-vben-admin后台管理系统',
//   //         '9、待整理/project/写一个VSCode扩展',
//   //         '9、待整理/project/某习通小助手',
//   //         '9、待整理/project/题小侠',
//   //         '9、待整理/reference/2020 · 编程之旅-起点',
//   //         '9、待整理/reference/2021 · 休学一年',
//   //         '9、待整理/reference/2022 · 逆向到Web开发',
//   //         '9、待整理/reference/2023 · 谈谈职业规划',
//   //         '9、待整理/reference/myfirst_reference_blog',
//   //         '9、待整理/reference/叙一名转专业+休学的大学生经历',
//   //         '9、待整理/skill/algorithm/algorithm-introduction',
//   //         '9、待整理/skill/algorithm/double-pointer',
//   //         '9、待整理/skill/algorithm/hash-table',
//   //         '9、待整理/skill/algorithm/sliding-window',
//   //         '9、待整理/skill/algorithm/three-sum',
//   //         '9、待整理/skill/algorithm/two-sum',
//   //         '9、待整理/skill/code-specification/code-specification-guides',
//   //         '9、待整理/skill/code-specification/editorconfig',
//   //         '9、待整理/skill/code-specification/eslint',
//   //         '9、待整理/skill/code-specification/husky',
//   //         '9、待整理/skill/code-specification/npmrc',
//   //         '9、待整理/skill/code-specification/prettier',
//   //         '9、待整理/skill/code-specification/stylelint',
//   //         '9、待整理/skill/database/elasticsearch/elasticsearch-note',
//   //         '9、待整理/skill/database/mongo/mongodb-note',
//   //         '9、待整理/skill/database/mysql/mysql-like-optimization',
//   //         '9、待整理/skill/database/mysql/mysql-note',
//   //         '9、待整理/skill/database/mysql/mysql-replace-function',
//   //         '9、待整理/skill/database/redis/redis-note',
//   //         '9、待整理/skill/docker/docker',
//   //         '9、待整理/skill/docker/docker-accesses-host-service',
//   //         '9、待整理/skill/docker/docker-compose',
//   //         '9、待整理/skill/docker/docker-container-log-clean',
//   //         '9、待整理/skill/docker/docker-deploy-node-project',
//   //         '9、待整理/skill/docker/fix-docker-config-that-cannot-start-up',
//   //         '9、待整理/skill/git/git-change-default-branch',
//   //         '9、待整理/skill/git/git-conmit-specification',
//   //         '9、待整理/skill/git/git-push-multiple-remote-repos',
//   //         '9、待整理/skill/git/github-actions-example',
//   //         '9、待整理/skill/git/github-apps-example',
//   //         '9、待整理/skill/git/github-other',
//   //         '9、待整理/skill/introduction',
//   //         '9、待整理/skill/js&ts/commonly-used-util.js',
//   //         '9、待整理/skill/js&ts/how-does-js-get-today-zero-timestamp',
//   //         '9、待整理/skill/js&ts/js-array-object-unique',
//   //         '9、待整理/skill/js&ts/js-implement-function-cache',
//   //         '9、待整理/skill/js&ts/js-print-stack-of-function',
//   //         '9、待整理/skill/js&ts/polymorphic-elimination-conditional-branching-refactor',
//   //         '9、待整理/skill/js&ts/querystring-and-json-convert',
//   //         '9、待整理/skill/js&ts/type-of-object-map-refactor',
//   //         '9、待整理/skill/js&ts/typescript-advanced-grammar',
//   //         '9、待整理/skill/misc/look-up-port-and-kill-process',
//   //         '9、待整理/skill/node/axios-request-gbk-page-encoding-solution',
//   //         '9、待整理/skill/node/npkill-quickly-move-node-modules',
//   //         '9、待整理/skill/node/npm-mirror-config',
//   //         '9、待整理/skill/node/use-require.context-to-auto-import-modules',
//   //         '9、待整理/skill/programming-languages/go/go-call-js',
//   //         '9、待整理/skill/programming-languages/go/go-concurrent',
//   //         '9、待整理/skill/programming-languages/go/go-environment-install',
//   //         '9、待整理/skill/programming-languages/go/go-json-usage',
//   //         '9、待整理/skill/programming-languages/go/go-send-http-request',
//   //         '9、待整理/skill/programming-languages/go/try-gin-framework',
//   //         '9、待整理/skill/programming-languages/java/Java反射',
//   //         '9、待整理/skill/programming-languages/python/pyautogui',
//   //         '9、待整理/skill/programming-languages/python/python-cv2-usage',
//   //         '9、待整理/skill/programming-languages/python/python-specified-versiton-run',
//   //         '9、待整理/skill/programming-languages/python/python-spider-summary',
//   //         '9、待整理/skill/reverse/android/frida/frida-java-encryption-algorithm',
//   //         '9、待整理/skill/reverse/android/frida/frida-note',
//   //         '9、待整理/skill/reverse/android/frida/frida-python-usage',
//   //         '9、待整理/skill/reverse/android/frida/frida-so-hook',
//   //         '9、待整理/skill/reverse/android/frida/objection-note',
//   //         '9、待整理/skill/reverse/android/刷机/brush-magisk',
//   //         '9、待整理/skill/reverse/android/刷机/install-lsposed',
//   //         '9、待整理/skill/reverse/android/刷机/intercepting-requests',
//   //         '9、待整理/skill/reverse/android/刷机/solution-of-bootloader-lock',
//   //         '9、待整理/skill/reverse/crypto/brief-talk-encryption-algorithm',
//   //         '9、待整理/skill/reverse/web/how-to-decompiling-miniprogram',
//   //         '9、待整理/skill/reverse/web/js-code-obfuscation-and-reverse',
//   //         '9、待整理/skill/web/browser/brower-copy-console-panel-output',
//   //         '9、待整理/skill/web/css/css-properties',
//   //         '9、待整理/skill/web/react/React中Css几种实现方案',
//   //         '9、待整理/skill/web/react/react-hooks',
//   //         '9、待整理/skill/web/vue/pinia',
//   //         '9、待整理/skill/web/vue/vue-reactive-data-array',
//   //         '9、待整理/skill/web/vue/vue-reactive-data-basic-type',
//   //         '9、待整理/skill/web/vue/vue-reactive-data-object',
//   //         '9、待整理/tools/everything-quick-search-local-files',
//   //         '9、待整理/tools/idea-config',
//   //         '9、待整理/tools/introduction',
//   //         '9、待整理/tools/jetbrains-product-activation-method',
//   //         '9、待整理/tools/tools-win系统录制GIF工具',
//   //         '9、待整理/tools/vite-plugin',
//   //         '9、待整理/tools/vscode-config',
//   //         '9、待整理/tools/wappalyzer-recognize-technology',
//   //         '9、待整理/tools/windows-custom-right-click-menu',
//   //         '9、待整理/tools/windows-terminal-beautify',
//   //         '9、待整理/其他博客信息/docs/Stack/C_C++/blank',
//   //         '9、待整理/其他博客信息/docs/Stack/PlanningControl/blank',
//   //         '9、待整理/其他博客信息/docs/Stack/ROS/blank',
//   //         '9、待整理/其他博客信息/docs/Stack/STM32/blank',
//   //         '9、待整理/未命名',
//   //         '9、待整理/错误日志'
//   //       ],
//   //   },
//   // ],

//   /*
//    linux: [{ type: 'autogenerated', dirName: '1、笔记数据/1、运维' }],
//   code: [{ type: 'autogenerated', dirName: '1、笔记数据/2、编程' }],
//   qianduan: [{ type: 'autogenerated', dirName: '1、笔记数据/3、前端' }],
//   hacker: [{ type: 'autogenerated', dirName: '1、笔记数据/4、黑客' }],
//   test: [{ type: 'autogenerated', dirName: '1、笔记数据/5、测试' }],
//   ai: [{ type: 'autogenerated', dirName: '1、笔记数据/6、AI' }],
//  */

//   //开源项目

//   opensource: [{ type: 'autogenerated', dirName: '2、开源项目' }],
//   // typora: [{ type: 'autogenerated', dirName: '2、开源项目/1、玩转Typora' }],
//   // Docusaurus: [{ type: 'autogenerated', dirName: '2、开源项目/2、玩转Docusaurus' }],
//   // home: [{ type: 'autogenerated', dirName: '2、开源项目/3、个人主页home3.0' }],
//   // ruyublog: [{ type: 'autogenerated', dirName: '2、开源项目/4、ruyu-blog' }],

//   //专题
//   website: [{ type: 'autogenerated', dirName: '3、专题/01、网站搭建' }],
//   cloudnote: [{ type: 'autogenerated', dirName: '3、专题/02、云笔记最佳实践' }],
//   wiki: [{ type: 'autogenerated', dirName: '3、专题/03、知识库选型' }],
//   shell: [
//     {
//       type: 'autogenerated',
//       dirName: '1、笔记数据/1、运维/1、linux/2、shell/4、shell脚本',
//     },
//   ],
//   nas: [{ type: 'autogenerated', dirName: '3、专题/05、NAS' }],
//   vscode: [
//     {
//       type: 'autogenerated',
//       dirName: '1、笔记数据/1、运维/5、other/文本编辑软件/1、vscode',
//     },
//   ],

//   //精神世界
//   life: [{ type: 'autogenerated', dirName: '4、精神世界/生活' }],
//   one: [{ type: 'autogenerated', dirName: '4、精神世界/终将释怀' }],

//   //关于我
//   aboutMyWebsite: [{ type: 'autogenerated', dirName: '5、关于我/关于本站' }],
// };

// export default sidebars;
